/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class AlbumSalesVO {
    public var album:AlbumVO;
    public var albumBuyCount:int;
    public var completionCount:int;
    public var albumBuyRevenue:Number;
    public var completionRevenue:Number;
    public var quarterArtistOwed:Number;
    public var recCountQuarter:int;

    public function AlbumSalesVO(remote:Object = null) {
      if(remote != null) {
        album = new AlbumVO(remote.album);
        albumBuyCount = remote.albumBuyCount;
        completionCount = remote.completionCount;
        albumBuyRevenue = remote.albumBuyRevenue;
        completionRevenue = remote.completionRevenue;
        quarterArtistOwed = remote.quarterArtistOwed;
        recCountQuarter = remote.recCountQuarter;
      }
    }
  }
}
