/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class AlbumSongVO {
    public var id:String;
    public var title:String;
    public var url:String;

    public function AlbumSongVO(remote:Object = null) {
      if(remote != null) {
        id = remote.id;
        title = remote.title;
        url = remote.url;
      }
    }
  }
}
