/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class AlbumVO {
    public var id:String;
    public var title:String;
    public var artist:ArtistVO;
    public var url:String;
    public var image:ImageVO;
    public var genres:Array;
    public var trackCount:int;
    public var price:Number;
    public var releaseDate:int;
    public var discCount:int;
    public var releaseDateString:String;

    public function AlbumVO(remote:Object = null) {
      if(remote != null) {
        id = remote.id;
        title = remote.title;
        artist = new ArtistVO(remote.artist);
        url = remote.url;
        image = new ImageVO(remote.image);
        genres = ThriftUtils.makeList(GenreVO, remote.genres);
        trackCount = remote.trackCount;
        price = remote.price;
        releaseDate = remote.releaseDate;
        discCount = remote.discCount;
        releaseDateString = remote.releaseDateString;
      }
    }
  }
}
