/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class AmieApiException {
    public var code:int;
    public var message:String;

    public function AmieApiException(remote:Object = null) {
      if(remote != null) {
        code = new int(remote.code);
        message = new String(remote.message);
      }
    }
  }
}
