/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class ArtistVO {
    public var id:String;
    public var name:String;
    public var url:String;
    public var image:ImageVO;

    public function ArtistVO(remote:Object = null) {
      if(remote != null) {
        id = remote.id;
        name = remote.name;
        url = remote.url;
        image = new ImageVO(remote.image);
      }
    }
  }
}
