/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class ArtistProfileVO {
    public var artist:ArtistVO;
    public var albumList:Array;

    public function ArtistProfileVO(remote:Object = null) {
      if(remote != null) {
        artist = new ArtistVO(remote.artist);
        albumList = ThriftUtils.makeList(AlbumVO, remote.albumList);
      }
    }
  }
}
