/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class CreateUserResponseVO {
    public var fingerprint:String;
    public var id:String;
    public var username:String;
    public var is_password_autogenerated:Boolean;
    public var password:String;

    public function CreateUserResponseVO(remote:Object = null) {
      if(remote != null) {
        fingerprint = remote.fingerprint;
        id = remote.id;
        username = remote.username;
        is_password_autogenerated = remote.is_password_autogenerated;
        password = remote.password;
      }
    }
  }
}
