/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class GenreGroupVO {
    public var id:String;
    public var name:String;
    public var dasherized_name:String;

    public function GenreGroupVO(remote:Object = null) {
      if(remote != null) {
        id = remote.id;
        name = remote.name;
        dasherized_name = remote.dasherized_name;
      }
    }
  }
}
