/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class GenreVO {
    public var name:String;
    public var primary_genre_group_id:String;
    public var id:String;

    public function GenreVO(remote:Object = null) {
      if(remote != null) {
        name = remote.name;
        primary_genre_group_id = remote.primary_genre_group_id;
        id = remote.id;
      }
    }
  }
}
