/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class HypemachineSongVO {
    public var mediaid:int;
    public var artist:String;
    public var title:String;
    public var dateposted:int;
    public var siteid:int;
    public var sitename:String;
    public var siteurl:String;
    public var posturl:String;

    public function HypemachineSongVO(remote:Object = null) {
      if(remote != null) {
        mediaid = remote.mediaid;
        artist = remote.artist;
        title = remote.title;
        dateposted = remote.dateposted;
        siteid = remote.siteid;
        sitename = remote.sitename;
        siteurl = remote.siteurl;
        posturl = remote.posturl;
      }
    }
  }
}
