/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  import flash.net.Responder;
  import flash.net.NetConnection;

  public class LastfmApi {
    private var connection:NetConnection;

    public function LastfmApi(conn:NetConnection) {
      connection = conn;
    }

    public function userTopArtists(user:String, period:String, onSuccess:Function = null, onError:Function = null):void {
      var resp:Responder = new Responder(
        function(result:Array):void {
          if(onSuccess != null) {
            onSuccess(ThriftUtils.makeList(LastfmArtistVO, result));
          }
        },
        function(error:Object):void {
          if(onError != null) {
            onError(error);
          }
        });
      connection.call('LastfmApi.userTopArtists', resp, {user: user, period: period});
    } // end userTopArtists

  }
}
