/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class LastfmArtistVO {
    public var name:String;
    public var url:String;
    public var playcount:int;
    public var images:Array;

    public function LastfmArtistVO(remote:Object = null) {
      if(remote != null) {
        name = remote.name;
        url = remote.url;
        playcount = remote.playcount;
        images = ThriftUtils.makeList(String, remote.images);
      }
    }
  }
}
