/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class NewsletterItemVO {
    public var id:String;
    public var newsletter_id:String;
    public var album:AlbumVO;
    public var title:String;
    public var blurb:String;

    public function NewsletterItemVO(remote:Object = null) {
      if(remote != null) {
        id = remote.id;
        newsletter_id = remote.newsletter_id;
        album = new AlbumVO(remote.album);
        title = remote.title;
        blurb = remote.blurb;
      }
    }
  }
}
