/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class NewsletterVO {
    public var id:String;
    public var name:String;
    public var subject:String;
    public var opening:String;
    public var status:String;
    public var sent_date:String;

    public function NewsletterVO(remote:Object = null) {
      if(remote != null) {
        id = remote.id;
        name = remote.name;
        subject = remote.subject;
        opening = remote.opening;
        status = remote.status;
        sent_date = remote.sent_date;
      }
    }
  }
}
