/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class PagedArtistListVO {
    public var page:int;
    public var limit:int;
    public var hasNext:Boolean;
    public var artists:Array;

    public function PagedArtistListVO(remote:Object = null) {
      if(remote != null) {
        page = remote.page;
        limit = remote.limit;
        hasNext = remote.hasNext;
        artists = ThriftUtils.makeList(ArtistVO, remote.artists);
      }
    }
  }
}
