/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class PagedSongListVO {
    public var page:int;
    public var limit:int;
    public var hasNext:Boolean;
    public var songs:Array;

    public function PagedSongListVO(remote:Object = null) {
      if(remote != null) {
        page = remote.page;
        limit = remote.limit;
        hasNext = remote.hasNext;
        songs = ThriftUtils.makeList(SongVO, remote.songs);
      }
    }
  }
}
