/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class PagedAlbumListVO {
    public var page:int;
    public var limit:int;
    public var hasNext:Boolean;
    public var albums:Array;

    public function PagedAlbumListVO(remote:Object = null) {
      if(remote != null) {
        page = remote.page;
        limit = remote.limit;
        hasNext = remote.hasNext;
        albums = ThriftUtils.makeList(AlbumVO, remote.albums);
      }
    }
  }
}
