/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class PandoraBookmarkedSongVO {
    public var title:String;
    public var album:String;
    public var artist:String;
    public var albumArtUrl:String;

    public function PandoraBookmarkedSongVO(remote:Object = null) {
      if(remote != null) {
        title = remote.title;
        album = remote.album;
        artist = remote.artist;
        albumArtUrl = remote.albumArtUrl;
      }
    }
  }
}
