/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class PandoraArtistSeedVO {
    public var name:String;

    public function PandoraArtistSeedVO(remote:Object = null) {
      if(remote != null) {
        name = remote.name;
      }
    }
  }
}
