/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class PandoraStationVO {
    public var name:String;
    public var stationCode:String;
    public var stationLink:String;
    public var listenerLink:String;
    public var songSeeds:Array;
    public var artistSeeds:Array;

    public function PandoraStationVO(remote:Object = null) {
      if(remote != null) {
        name = remote.name;
        stationCode = remote.stationCode;
        stationLink = remote.stationLink;
        listenerLink = remote.listenerLink;
        songSeeds = ThriftUtils.makeList(PandoraSongSeedVO, remote.songSeeds);
        artistSeeds = ThriftUtils.makeList(PandoraArtistSeedVO, remote.artistSeeds);
      }
    }
  }
}
