/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  import flash.net.Responder;
  import flash.net.NetConnection;

  public class PandoraApi {
    private var connection:NetConnection;

    public function PandoraApi(conn:NetConnection) {
      connection = conn;
    }

    public function stations(user:String, onSuccess:Function = null, onError:Function = null):void {
      var resp:Responder = new Responder(
        function(result:Array):void {
          if(onSuccess != null) {
            onSuccess(ThriftUtils.makeList(PandoraStationVO, result));
          }
        },
        function(error:Object):void {
          if(onError != null) {
            onError(error);
          }
        });
      connection.call('PandoraApi.stations', resp, {user: user});
    } // end stations

    public function bookmarkedSongs(user:String, onSuccess:Function = null, onError:Function = null):void {
      var resp:Responder = new Responder(
        function(result:Array):void {
          if(onSuccess != null) {
            onSuccess(ThriftUtils.makeList(PandoraBookmarkedSongVO, result));
          }
        },
        function(error:Object):void {
          if(onError != null) {
            onError(error);
          }
        });
      connection.call('PandoraApi.bookmarkedSongs', resp, {user: user});
    } // end bookmarkedSongs

    public function bookmarkedArtists(user:String, onSuccess:Function = null, onError:Function = null):void {
      var resp:Responder = new Responder(
        function(result:Array):void {
          if(onSuccess != null) {
            onSuccess(ThriftUtils.makeList(PandoraBookmarkedArtistVO, result));
          }
        },
        function(error:Object):void {
          if(onError != null) {
            onError(error);
          }
        });
      connection.call('PandoraApi.bookmarkedArtists', resp, {user: user});
    } // end bookmarkedArtists

  }
}
