/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class PandoraSongSeedVO {
    public var title:String;
    public var artist:String;

    public function PandoraSongSeedVO(remote:Object = null) {
      if(remote != null) {
        title = remote.title;
        artist = remote.artist;
      }
    }
  }
}
