/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  import flash.net.Responder;
  import flash.net.NetConnection;

  public class PlayerApi {
    private var connection:NetConnection;

    public function PlayerApi(conn:NetConnection) {
      connection = conn;
    }

    public function scrobble(fingerprint:String, songId:String, status:String, instance:String, onSuccess:Function = null, onError:Function = null):void {
      var resp:Responder = new Responder(
        function(result:Object):void {
          if(onSuccess != null) {
            onSuccess(new ScrobbleResponseVO(result));
          }
        },
        function(error:Object):void {
          if(onError != null) {
            onError(error);
          }
        });
      connection.call('PlayerApi.scrobble', resp, {fingerprint: fingerprint, songId: songId, status: status, instance: instance});
    } // end scrobble

  }
}
