/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class PlaylistProfileVO {
    public var playlist:PlaylistVO;
    public var collaborators:Array;
    public var songs:Array;

    public function PlaylistProfileVO(remote:Object = null) {
      if(remote != null) {
        playlist = new PlaylistVO(remote.playlist);
        collaborators = ThriftUtils.makeList(PlaylistCollaboratorVO, remote.collaborators);
        songs = ThriftUtils.makeList(SongVO, remote.songs);
      }
    }
  }
}
