/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class PlayHistoryVO {
    public var timestamp:String;
    public var song:SongVO;

    public function PlayHistoryVO(remote:Object = null) {
      if(remote != null) {
        timestamp = remote.timestamp;
        song = new SongVO(remote.song);
      }
    }
  }
}
