/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class PlaylistCollaboratorVO {
    public var id:String;
    public var username:String;
    public var url:String;

    public function PlaylistCollaboratorVO(remote:Object = null) {
      if(remote != null) {
        id = remote.id;
        username = remote.username;
        url = remote.url;
      }
    }
  }
}
