/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class RecommendationVO {
    public var album:AlbumVO;
    public var reasons:Array;

    public function RecommendationVO(remote:Object = null) {
      if(remote != null) {
        album = new AlbumVO(remote.album);
        reasons = ThriftUtils.makeList(RecommendationsSeedArtistVO, remote.reasons);
      }
    }
  }
}
