/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class RecommendationsSeedArtistVO {
    public var name:String;
    public var source:String;
    public var added_on:String;
    public var url:String;
    public var id:String;

    public function RecommendationsSeedArtistVO(remote:Object = null) {
      if(remote != null) {
        name = remote.name;
        source = remote.source;
        added_on = remote.added_on;
        url = remote.url;
        id = remote.id;
      }
    }
  }
}
