/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class RecVO {
    public var id:String;
    public var review:String;
    public var sounds_like:String;
    public var user:UserVO;
    public var song:SongVO;

    public function RecVO(remote:Object = null) {
      if(remote != null) {
        id = new String(remote.id);
        review = remote.review;
        sounds_like = remote.sounds_like;
        user = new UserVO(remote.user);
        song = new SongVO(remote.song);
      }
    }
  }
}
