/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  import flash.net.Responder;
  import flash.net.NetConnection;

  public class SalesReportApi {
    private var connection:NetConnection;

    public function SalesReportApi(conn:NetConnection) {
      connection = conn;
    }

    public function getBasicSalesReport(quarter:int, year:int, onSuccess:Function = null, onError:Function = null):void {
      var resp:Responder = new Responder(
        function(result:Object):void {
          if(onSuccess != null) {
            onSuccess(new BasicSalesReportVO(result));
          }
        },
        function(error:Object):void {
          if(onError != null) {
            onError(error);
          }
        });
      connection.call('SalesReportApi.getBasicSalesReport', resp, {quarter: quarter, year: year});
    } // end getBasicSalesReport

  }
}
