/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class ScrobbleResponseVO {
    public var user_id:String;
    public var status:String;
    public var instance:String;
    public var song:SongVO;
    public var procedures:ScrobbleProcedures;

    public function ScrobbleResponseVO(remote:Object = null) {
      if(remote != null) {
        user_id = remote.user_id;
        status = remote.status;
        instance = remote.instance;
        song = new SongVO(remote.song);
        procedures = new ScrobbleProcedures(remote.procedures);
      }
    }
  }
}
