/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class ScrobbleProcedures {
    public var lastfm:Boolean;
    public var twitter:Boolean;

    public function ScrobbleProcedures(remote:Object = null) {
      if(remote != null) {
        lastfm = remote.lastfm;
        twitter = remote.twitter;
      }
    }
  }
}
