/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class SearchFindResults {
    public var artists:Array;
    public var songs:Array;

    public function SearchFindResults(remote:Object = null) {
      if(remote != null) {
        artists = ThriftUtils.makeList(SearchFindArtistResult, remote.artists);
        songs = ThriftUtils.makeList(SearchFindSongResult, remote.songs);
      }
    }
  }
}
