/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class SearchFindSongResult {
    public var query:String;
    public var found:Boolean;
    public var id:String;
    public var title:String;
    public var url:String;
    public var artistNameQuery:String;
    public var artistId:String;

    public function SearchFindSongResult(remote:Object = null) {
      if(remote != null) {
        query = remote.query;
        found = remote.found;
        id = new String(remote.id);
        title = remote.title;
        url = remote.url;
        artistNameQuery = remote.artistNameQuery;
        artistId = new String(remote.artistId);
      }
    }
  }
}
