/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class ShrekResult {
    public var sourceArtist:ShrekAutoCompleteArtist;
    public var artist:ArtistVO;
    public var relationships:Array;

    public function ShrekResult(remote:Object = null) {
      if(remote != null) {
        sourceArtist = new ShrekAutoCompleteArtist(remote.sourceArtist);
        artist = new ArtistVO(remote.artist);
        relationships = ThriftUtils.makeList(ShrekRelationship, remote.relationships);
      }
    }
  }
}
