/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class ShrekRelationship {
    public var inverse:Boolean;
    public var sourceArtist:ShrekAutoCompleteArtist;
    public var type:String;
    public var type_desc:String;
    public var weight:int;

    public function ShrekRelationship(remote:Object = null) {
      if(remote != null) {
        inverse = remote.inverse;
        sourceArtist = new ShrekAutoCompleteArtist(remote.sourceArtist);
        type = remote.type;
        type_desc = remote.type_desc;
        weight = remote.weight;
      }
    }
  }
}
