/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class SongzaSongVO {
    public var id:String;
    public var artist:String;
    public var song:String;
    public var link:String;

    public function SongzaSongVO(remote:Object = null) {
      if(remote != null) {
        id = remote.id;
        artist = remote.artist;
        song = remote.song;
        link = remote.link;
      }
    }
  }
}
