/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  import flash.net.Responder;
  import flash.net.NetConnection;

  public class SongApi {
    private var connection:NetConnection;

    public function SongApi(conn:NetConnection) {
      connection = conn;
    }

    public function getSongById(id:String, onSuccess:Function = null, onError:Function = null):void {
      var resp:Responder = new Responder(
        function(result:Object):void {
          if(onSuccess != null) {
            onSuccess(new SongVO(result));
          }
        },
        function(error:Object):void {
          if(onError != null) {
            onError(error);
          }
        });
      connection.call('SongApi.getSongById', resp, {id: id});
    } // end getSongById

    public function recordPostPurchasePlay(id:String, onSuccess:Function = null, onError:Function = null):void {
      var resp:Responder = new Responder(
        function(result:Object):void {
          if(onSuccess != null) {
            onSuccess(new Boolean(result));
          }
        },
        function(error:Object):void {
          if(onError != null) {
            onError(error);
          }
        });
      connection.call('SongApi.recordPostPurchasePlay', resp, {id: id});
    } // end recordPostPurchasePlay

    public function getUsersWhoPurchasedWithPrices(song:String, offset:int, limit:int, onSuccess:Function = null, onError:Function = null):void {
      var resp:Responder = new Responder(
        function(result:Array):void {
          if(onSuccess != null) {
            onSuccess(ThriftUtils.makeList(UserWithPriceVO, result));
          }
        },
        function(error:Object):void {
          if(onError != null) {
            onError(error);
          }
        });
      connection.call('SongApi.getUsersWhoPurchasedWithPrices', resp, {song: song, offset: offset, limit: limit});
    } // end getUsersWhoPurchasedWithPrices

  }
}
