/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class SongVO {
    public var id:String;
    public var title:String;
    public var album:AlbumVO;
    public var artist:ArtistVO;
    public var url:String;
    public var length:int;
    public var recs:int;
    public var trackNumber:int;
    public var price:Number;
    public var actorHasSong:Boolean;
    public var actorHasRecd:Boolean;
    public var actorOwnsAlbum:Boolean;
    public var actorCanCompleteAlbum:Boolean;
    public var discNumber:int;
    public var discTrackNumber:int;
    public var discTrackCount:int;
    public var pppLength:int;

    public function SongVO(remote:Object = null) {
      if(remote != null) {
        id = remote.id;
        title = remote.title;
        album = new AlbumVO(remote.album);
        artist = new ArtistVO(remote.artist);
        url = remote.url;
        length = remote.length;
        recs = remote.recs;
        trackNumber = remote.trackNumber;
        price = remote.price;
        actorHasSong = remote.actorHasSong;
        actorHasRecd = remote.actorHasRecd;
        actorOwnsAlbum = remote.actorOwnsAlbum;
        actorCanCompleteAlbum = remote.actorCanCompleteAlbum;
        discNumber = remote.discNumber;
        discTrackNumber = remote.discTrackNumber;
        discTrackCount = remote.discTrackCount;
        pppLength = remote.pppLength;
      }
    }
  }
}
