/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class TagVO {
    public var tag:String;
    public var score:int;

    public function TagVO(remote:Object = null) {
      if(remote != null) {
        tag = remote.tag;
        score = remote.score;
      }
    }
  }
}
