/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  import flash.net.Responder;
  import flash.net.NetConnection;

  public class TumblrApi {
    private var connection:NetConnection;

    public function TumblrApi(conn:NetConnection) {
      connection = conn;
    }

    public function newPost(email:String, password:String, title:String, body:String, tags:String, group:String, onSuccess:Function = null, onError:Function = null):void {
      var resp:Responder = new Responder(
        function(result:Object):void {
          if(onSuccess != null) {
            onSuccess(new Boolean(result));
          }
        },
        function(error:Object):void {
          if(onError != null) {
            onError(error);
          }
        });
      connection.call('TumblrApi.newPost', resp, {email: email, password: password, title: title, body: body, tags: tags, group: group});
    } // end newPost

  }
}
