/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class UserWithPriceVO {
    public var user:UserVO;
    public var price:Number;

    public function UserWithPriceVO(remote:Object = null) {
      if(remote != null) {
        user = new UserVO(remote.user);
        price = remote.price;
      }
    }
  }
}
