/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.amiestreet.api {

  [Bindable]
  dynamic public class VideoVO {
    public var id:String;
    public var provider:String;
    public var provider_id:String;
    public var title:String;
    public var artist_id:String;
    public var song_id:String;

    public function VideoVO(remote:Object = null) {
      if(remote != null) {
        id = remote.id;
        provider = remote.provider;
        provider_id = remote.provider_id;
        title = remote.title;
        artist_id = remote.artist_id;
        song_id = remote.song_id;
      }
    }
  }
}
